Feature/ga 092
Aikodev-labs/Ghibli-API-platform pull request #105
Opened 2023-12-01 10:54 UTC by juanpablo1978

Hola a todos, buenos dias!

Les dejo el componente ClipBoard, tengo dudas de si es lo que se esperaba para la tarea porque en mi caso utilicé una libreria de npm para React.
En la carpeta "docs" del visual documenté el componente para que puedan tener una idea de cómo utilizarlo.
Les dejo una vista de ejemplo: 

![clipboardprint](https://github.com/Aikodev-labs/Ghibli-API-platform/assets/86315284/56a82584-d85b-4aac-abc2-a5f398acfdbb)

2023-12-01 11:13 UTC, RosselloAgustin approved these changes

2023-12-01 19:44 UTC, aikolabs commented
Hola Juan, en realidad se podía hacer desde cero o a través de una librería. Quedó como caso de investigación y se ve que lo lograste.

2023-12-01 20:02 UTC, aikolabs commented on docs/ClipBoard.md
Esta completa la documentación

2023-12-01 20:09 UTC, aikolabs requested changes
Quizá no subiste todos los cambios, pero en el caso de que sean todos los cambios, por favor trabajar en los puntos que mencioné.

2023-12-06 22:09 UTC, DesSussu commented
Hola Juan. Queda genial, igual con el icono este que son como dos cuadrados superpuestos creo queda un poco más actual. Pero aún así lo veo genial!

2024-11-13 11:20 UTC, closed without merging